"use client";

import { useState, useRef, useEffect } from "react";

interface SupportMessage {
  id: string;
  sender: "bot" | "user";
  text: string;
  timestamp: string;
}

interface TicketInfo {
  id: string;
  category: string;
  priority: string;
  subject: string;
  message: string;
  status: string;
  timestamp: string;
}

const FAQ_SUGGESTIONS = [
  { question: "How do payouts work?", answer: "Withdrawals are supported starting at just 1,000 coins ($1.00 USD). You can cash out via PayPal, Litecoin (LTC), Bitcoin (BTC), and leading gift cards. Most payout requests are approved and processed by our review staff within 2 hours, and a maximum of 24 hours under security audits." },
  { question: "Why is my survey pending?", answer: "Some survey providers verify submissions manually to prevent speed-running or invalid data. This can take anywhere from 1 hour to 72 hours. If a survey lead is still pending after 72 hours, check the 'Offer Status' link inside your Offerwall panel, or open a support ticket below with details." },
  { question: "Can I use a VPN/Proxy?", answer: "No. BinnyCash has a strict zero-tolerance policy against VPNs, Proxies, VPS, and Emulators. Connecting through these routing networks will flag our fraud systems and result in an automated, permanent account ban." },
  { question: "How to earn referral commission?", answer: "Head to your Dashboard to grab your referral link. You earn a 10% lifetime commission on all reward earnings generated by users who register using your link. Referral points credit to your balance instantly!" },
];

export default function LiveSupport() {
  const [messages, setMessages] = useState<SupportMessage[]>([
    {
      id: "bot-init",
      sender: "bot",
      text: "Hello! Welcome to BinnyCash Live Support. I am Binny Bot, your interactive AI helper. Ask me any question, or select one of the common topics below. If you still need assistance, you can submit a support ticket below!",
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    },
  ]);
  const [inputText, setInputText] = useState("");
  const messagesContainerRef = useRef<HTMLDivElement>(null);

  // Support Ticket States
  const [category, setCategory] = useState("Survey Crediting");
  const [priority, setPriority] = useState("Medium");
  const [subject, setSubject] = useState("");
  const [ticketMessage, setTicketMessage] = useState("");
  const [createdTickets, setCreatedTickets] = useState<TicketInfo[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [ticketSuccess, setTicketSuccess] = useState(false);

  useEffect(() => {
    if (messagesContainerRef.current) {
      messagesContainerRef.current.scrollTop = messagesContainerRef.current.scrollHeight;
    }
  }, [messages]);

  const handleFAQClick = (faq: typeof FAQ_SUGGESTIONS[0]) => {
    const now = new Date();
    const userMsg: SupportMessage = {
      id: `user-${Date.now()}`,
      sender: "user",
      text: faq.question,
      timestamp: now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    };

    const botReply: SupportMessage = {
      id: `bot-${Date.now()}`,
      sender: "bot",
      text: faq.answer,
      timestamp: now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    };

    setMessages((prev) => [...prev, userMsg, botReply]);
  };

  const handleSendMessage = (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputText.trim()) return;

    const userText = inputText;
    const now = new Date();
    const userMsg: SupportMessage = {
      id: `user-${Date.now()}`,
      sender: "user",
      text: userText,
      timestamp: now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    };

    setMessages((prev) => [...prev, userMsg]);
    setInputText("");

    // Simulate Bot Response logic based on keywords
    setTimeout(() => {
      let botAnswer = "I'm sorry, I couldn't find an answer to that specific question. However, you can write a support ticket in the form below and our staff team will contact you under 2 hours!";
      const query = userText.toLowerCase();

      if (query.includes("vpn") || query.includes("proxy") || query.includes("ban") || query.includes("emulator")) {
        botAnswer = FAQ_SUGGESTIONS[2].answer;
      } else if (query.includes("payout") || query.includes("withdraw") || query.includes("cashout") || query.includes("paypal") || query.includes("crypto") || query.includes("ltc")) {
        botAnswer = FAQ_SUGGESTIONS[0].answer;
      } else if (query.includes("survey") || query.includes("pending") || query.includes("credit") || query.includes("points") || query.includes("coins")) {
        botAnswer = FAQ_SUGGESTIONS[1].answer;
      } else if (query.includes("referral") || query.includes("invite") || query.includes("friend") || query.includes("commission")) {
        botAnswer = FAQ_SUGGESTIONS[3].answer;
      } else if (query.includes("hello") || query.includes("hi") || query.includes("hey")) {
        botAnswer = "Hi there! How can I help you today? Please feel free to click any suggestion below or ask a question.";
      }

      setMessages((prev) => [
        ...prev,
        {
          id: `bot-reply-${Date.now()}`,
          sender: "bot",
          text: botAnswer,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        },
      ]);
    }, 1000);
  };

  const handleCreateTicket = (e: React.FormEvent) => {
    e.preventDefault();
    if (!subject.trim() || !ticketMessage.trim()) return;

    setIsSubmitting(true);

    // Simulate ticket creation server delay
    setTimeout(() => {
      const ticketId = `BC-${Math.floor(10000 + Math.random() * 90000)}`;
      const newTicket: TicketInfo = {
        id: ticketId,
        category,
        priority,
        subject,
        message: ticketMessage,
        status: "Open",
        timestamp: new Date().toLocaleString(),
      };

      setCreatedTickets((prev) => [newTicket, ...prev]);
      setIsSubmitting(false);
      setTicketSuccess(true);
      setSubject("");
      setTicketMessage("");
    }, 1500);
  };

  return (
    <section className="pt-32 pb-20 px-4 sm:px-6 max-w-7xl mx-auto w-full animate-fade-in relative">
      {/* Background Glows */}
      <div className="absolute top-1/3 left-10 w-80 h-80 bg-accent-green/5 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-1/3 right-10 w-80 h-80 bg-accent-purple/5 rounded-full blur-[120px] pointer-events-none" />

      {/* Header */}
      <div className="text-center mb-12">
        <span className="text-xs uppercase tracking-widest text-accent-purple font-bold">HELP DESK</span>
        <h1 className="text-3xl md:text-5xl font-extrabold font-display text-text-primary mt-2">
          Live Support & Ticket Center
        </h1>
        <p className="text-sm md:text-base text-text-secondary max-w-xl mx-auto mt-3">
          Get instant replies from our Support Bot or create a priority ticket to connect directly with our support specialists.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
        {/* Support Chat Assistant (Left/Top Col) */}
        <div className="lg:col-span-6 flex flex-col bg-card-bg border border-card-border rounded-3xl overflow-hidden h-[540px] md:h-[580px] shadow-2xl">
          {/* Chat Header */}
          <div className="p-4 md:p-5 bg-bg-secondary border-b border-card-border flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-accent-green/10 border border-accent-green/20 flex items-center justify-center text-accent-green font-bold text-lg">
                🤖
              </div>
              <div>
                <p className="text-sm font-bold text-text-primary">Binny Bot Assistant</p>
                <p className="text-[10px] text-accent-green font-semibold">Active & Online</p>
              </div>
            </div>
            <button
              onClick={() => setMessages([
                {
                  id: "bot-reset",
                  sender: "bot",
                  text: "Chat history cleared. How can I help you now?",
                  timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
                }
              ])}
              className="text-[10px] text-text-muted hover:text-text-primary hover:bg-white/5 border border-card-border px-2.5 py-1.5 rounded-lg transition-all cursor-pointer font-bold"
            >
              Reset Chat
            </button>
          </div>

          {/* Messages Window */}
          <div ref={messagesContainerRef} className="flex-1 overflow-y-auto p-4 md:p-5 flex flex-col gap-4 scrollbar-thin">
            {messages.map((msg) => (
              <div
                key={msg.id}
                className={`flex flex-col max-w-[85%] ${
                  msg.sender === "user" ? "self-end items-end" : "self-start items-start"
                }`}
              >
                <span className="text-[9px] text-text-muted mb-1 px-1">{msg.timestamp}</span>
                <div className={`p-3.5 rounded-2xl text-xs md:text-sm border leading-relaxed ${
                  msg.sender === "user"
                    ? "bg-accent-purple/20 border-accent-purple/30 text-white rounded-tr-none"
                    : "bg-bg-tertiary border-card-border text-text-secondary rounded-tl-none"
                }`}>
                  {msg.text}
                </div>
              </div>
            ))}
          </div>

          {/* Suggested FAQs Shortcuts */}
          <div className="p-3 bg-bg-secondary/40 border-t border-card-border flex flex-col gap-2">
            <p className="text-[10px] uppercase font-bold text-text-muted px-1">Common Questions:</p>
            <div className="flex flex-wrap gap-1.5 max-h-[85px] overflow-y-auto">
              {FAQ_SUGGESTIONS.map((faq, idx) => (
                <button
                  key={idx}
                  onClick={() => handleFAQClick(faq)}
                  className="px-2.5 py-1.5 rounded-lg bg-bg-tertiary border border-card-border text-[10px] font-bold text-text-secondary hover:text-text-primary hover:border-accent-purple transition-all cursor-pointer"
                >
                  {faq.question}
                </button>
              ))}
            </div>
          </div>

          {/* Input Area */}
          <form onSubmit={handleSendMessage} className="p-4 bg-bg-secondary border-t border-card-border flex gap-2">
            <input
              type="text"
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              placeholder="Ask support bot a question..."
              className="flex-1 px-4 py-3 bg-bg-primary border border-input-border text-text-primary rounded-xl text-xs md:text-sm outline-none focus:border-accent-purple transition-all placeholder:text-text-muted"
            />
            <button
              type="submit"
              className="w-11 h-11 bg-accent-purple hover:bg-[#7c3aed] text-white rounded-xl shadow-glow-purple flex items-center justify-center transition-all cursor-pointer"
            >
              <svg className="w-4 h-4 fill-current transform rotate-90" viewBox="0 0 24 24">
                <path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z" />
              </svg>
            </button>
          </form>
        </div>

        {/* Support Ticket Submission Form (Right Col) */}
        <div className="lg:col-span-6 flex flex-col gap-6">
          {/* Submit Form Card */}
          <div className="bg-card-bg border border-card-border p-6 md:p-8 rounded-3xl shadow-2xl flex flex-col justify-between">
            <div>
              <h3 className="text-lg font-bold font-display text-text-primary">Submit a Support Ticket</h3>
              <p className="text-xs text-text-secondary mt-1">If the helper bot couldn&apos;t answer your issue, open an official support ticket below.</p>
              
              {ticketSuccess && (
                <div className="bg-accent-green/10 border border-accent-green/20 text-accent-green p-4 rounded-xl mt-4 flex items-center justify-between text-xs md:text-sm animate-fade-in">
                  <div className="flex items-center gap-2">
                    <span className="text-lg">✓</span>
                    <div>
                      <p className="font-bold">Ticket Submitted Successfully!</p>
                      <p className="text-[10px] text-text-secondary mt-0.5">Estimated response time: Under 2 hours.</p>
                    </div>
                  </div>
                  <button
                    onClick={() => setTicketSuccess(false)}
                    className="text-[10px] font-bold underline bg-transparent border-none cursor-pointer"
                  >
                    Close
                  </button>
                </div>
              )}

              <form onSubmit={handleCreateTicket} className="flex flex-col gap-4 mt-6">
                <div className="grid grid-cols-2 gap-4">
                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] uppercase font-bold text-text-secondary">Category</label>
                    <select
                      value={category}
                      onChange={(e) => setCategory(e.target.value)}
                      className="px-3.5 py-2.5 bg-bg-primary border border-input-border text-text-primary rounded-xl text-xs outline-none focus:border-accent-purple font-semibold"
                    >
                      <option>Survey Crediting</option>
                      <option>Offerwall Issue</option>
                      <option>Payout Issue</option>
                      <option>Account Issue</option>
                      <option>Other / Suggestions</option>
                    </select>
                  </div>
                  
                  <div className="flex flex-col gap-1.5">
                    <label className="text-[10px] uppercase font-bold text-text-secondary">Priority</label>
                    <select
                      value={priority}
                      onChange={(e) => setPriority(e.target.value)}
                      className="px-3.5 py-2.5 bg-bg-primary border border-input-border text-text-primary rounded-xl text-xs outline-none focus:border-accent-purple font-semibold"
                    >
                      <option>Low</option>
                      <option>Medium</option>
                      <option>High</option>
                    </select>
                  </div>
                </div>

                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] uppercase font-bold text-text-secondary">Subject</label>
                  <input
                    type="text"
                    required
                    value={subject}
                    onChange={(e) => setSubject(e.target.value)}
                    placeholder="Brief description of the problem"
                    className="px-3.5 py-2.5 bg-bg-primary border border-input-border text-text-primary rounded-xl text-xs md:text-sm outline-none focus:border-accent-purple transition-all placeholder:text-text-muted font-semibold"
                  />
                </div>

                <div className="flex flex-col gap-1.5">
                  <label className="text-[10px] uppercase font-bold text-text-secondary">Detailed Message</label>
                  <textarea
                    required
                    rows={4}
                    value={ticketMessage}
                    onChange={(e) => setTicketMessage(e.target.value)}
                    placeholder="Describe your issue in detail. If it is an offerwall issue, please include the Offer ID if available..."
                    className="px-3.5 py-2.5 bg-bg-primary border border-input-border text-text-primary rounded-xl text-xs md:text-sm outline-none focus:border-accent-purple transition-all placeholder:text-text-muted resize-none leading-relaxed font-sans"
                  />
                </div>

                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="px-5 py-3.5 bg-accent-purple hover:bg-[#7c3aed] disabled:bg-accent-purple/50 disabled:cursor-not-allowed text-white text-xs md:text-sm font-bold rounded-xl shadow-glow-purple transition-all duration-300 cursor-pointer flex items-center justify-center gap-2 mt-2"
                >
                  {isSubmitting ? (
                    <>
                      <div className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      <span>Creating Ticket...</span>
                    </>
                  ) : (
                    <span>Submit Ticket</span>
                  )}
                </button>
              </form>
            </div>
          </div>

          {/* List of active tickets */}
          {createdTickets.length > 0 && (
            <div className="bg-card-bg border border-card-border p-6 rounded-3xl shadow-xl flex flex-col gap-4 max-h-[220px] overflow-y-auto scrollbar-thin">
              <h4 className="text-xs uppercase font-bold tracking-wider text-text-secondary">Active Tickets ({createdTickets.length})</h4>
              <div className="flex flex-col gap-3">
                {createdTickets.map((ticket) => (
                  <div key={ticket.id} className="p-3.5 bg-bg-tertiary border border-card-border rounded-2xl flex flex-col gap-2">
                    <div className="flex items-center justify-between">
                      <span className="text-[11px] font-bold text-accent-green">{ticket.id}</span>
                      <span className={`px-2 py-0.5 border text-[9px] font-bold rounded-md ${
                        ticket.priority === "High" ? "bg-red-500/10 border-red-500/20 text-red-400" :
                        ticket.priority === "Medium" ? "bg-amber-500/10 border-amber-500/20 text-amber-400" :
                        "bg-white/5 border-white/10 text-text-muted"
                      }`}>
                        {ticket.priority} Priority
                      </span>
                    </div>
                    <div>
                      <p className="text-xs font-bold text-text-primary">{ticket.subject}</p>
                      <p className="text-[10px] text-text-secondary mt-1 line-clamp-2">{ticket.message}</p>
                    </div>
                    <div className="flex items-center justify-between border-t border-white/5 pt-2 mt-1">
                      <span className="text-[9px] text-text-muted">{ticket.timestamp}</span>
                      <span className="px-2 py-0.5 rounded-full bg-accent-green/20 border border-accent-green/30 text-accent-green text-[9px] font-bold">
                        {ticket.status}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
